force-app/main/default/objects/Opportunity/fields/Account_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Account_Legal_Entity__c</fullName>
    <formula>Text(Account.Account_Legal_Entity__c)</formula>
    <label>Account Legal Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>If Rejected Reason is required</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval In Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <description>This field will capture the Billing Address from the Account.</description>
    <inlineHelpText>This field will be populated from Account Billing address once opportunity is created.</inlineHelpText>
    <label>Billing Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field will capture the Billing contact from the Account. This can be updated later.</description>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Record_Type_Name__c</field>
            <operation>notEqual</operation>
            <value>Agency</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Record_Type_Name__c</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Billing Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <formula>Account.BillingCountry</formula>
    <label>Billing Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Free_Trial_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Free_Trial_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will capture the AM’s choice about creation of free trial IO.</description>
    <label>Is Free Trial Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Segment__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Segment__c</fullName>
    <label>Opportunity Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Opportunity_SubType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Mediation</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Primary Mediation</fullName>
            </value>
            <value>
                <fullName>Programmatic</fullName>
            </value>
            <value>
                <fullName>Monetization Partner</fullName>
            </value>
            <value>
                <fullName>White Label partner</fullName>
            </value>
            <value>
                <fullName>Offsite</fullName>
            </value>
            <value>
                <fullName>Video/SPA/Display</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Audience</fullName>
                <isActive>false</isActive>
                <label>Audience</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_SubType__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_SubType__c</fullName>
    <label>Opportunity SubType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meson Prime</fullName>
            </value>
            <value>
                <fullName>Meson Wrap</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Gaming - Supply</fullName>
            </value>
            <value>
                <fullName>Non Gaming - Supply</fullName>
            </value>
            <value>
                <fullName>Demand</fullName>
            </value>
            <value>
                <fullName>Glance</fullName>
            </value>
            <value>
                <fullName>PMP</fullName>
            </value>
            <value>
                <fullName>Etisalat</fullName>
            </value>
            <value>
                <fullName>Appsumer</fullName>
            </value>
            <value>
                <fullName>Pulse</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <inlineHelpText>This field needs to be populated only in case of Exchange opportunity.</inlineHelpText>
    <label>PMP Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APMP</fullName>
            </value>
            <value>
                <fullName>DPMP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Demand.recordType-meta.xml
<RecordType>
    <fullName>Demand</fullName>
    <active>true</active>
    <businessProcess>Demand</businessProcess>
    <description>For IMC/Glance workflows</description>
    <label>Demand</label>
</RecordType>

force-app/main/default/classes/AzureOpportunityExtractionBatchTest.cls
@isTest
private class AzureOpportunityExtractionBatchTest {
    @isTest
    static void testAzureOpportunityExtractionBatch() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        AzureOpportunityExtractionBatch batch = new AzureOpportunityExtractionBatch();
        Database.executeBatch(batch);
        Test.stopTest();

    }
     @isTest
    static void testProcessRow(){
        Account ac = new Account();
        ac.Name = 'Test Acc';
        ac.Account_Type__c = 'Agency';
        ac.Account_Segment__c = 'Brand';
        ac.MasterAccountId__c = 'Test1234';
       // ac.Account_Stage__c = 'Draft';
        ac.Billing_Country__c = 'India';
        ac.BillingCountry = 'India';
        ac.Account_Legal_Entity__c = 'IMIN';
        ac.GST_Type__c = 'Regular/TDS/ISD';
        ac.GST_Number__c = '12345abcd';
        ac.PAN_Card_Detail__c = 'abcde1234k';
        //insert ac;
        //account acc = [select id, name from account limit 1];
        
        Contact con = New Contact();
        con.LastName = 'Test';
        con.AccountId = ac.Id;
       // insert con;
        
        
        
        Opportunity opp = New Opportunity();
        opp.Name = 'opty1';
        opp.AccountId = ac.Id;
        opp.Billing_Contact__c = con.Id;
        opp.Opportunity_Type__c = 'New Customer';
        opp.Billing_Address__c = 'Test Street';
        opp.StageName = 'Qualified';
        opp.CloseDate = Date.today() + 30;
        opp.Amount = 15000;
        opp.Type = 'New Business';
        opp.Opportunity_SubType__c = 'Demand';
        opp.Opportunity_Segment__c = 'Brand';
        opp.Approval_Status__c = 'Approved';
        opp.Is_Free_Trial_Required__c = true;
        //insert opp;
        // Start the batch
        AzureOpportunityExtractionBatch.processRow(opp);
    }
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'text/plain');
            response.setBody('Mock response');
            response.setStatusCode(200);
            return response;
        }
    }
    
}