force-app/main/default/objects/Opportunity/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Budget Cut</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Failed Trial</fullName>
            </value>
            <value>
                <fullName>Integration Issues</fullName>
            </value>
            <value>
                <fullName>Stopped responding</fullName>
            </value>
            <value>
                <fullName>No Interest</fullName>
            </value>
            <value>
                <fullName>Not a fit (rejected by InMobi)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Admin Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityStageController.cls
public with sharing class OpportunityStageController {
   
    @AuraEnabled
    public static List < Map < String, String >> getPickListValues(String strObjectName, String strPicklistField) {
        List < Map < String, String >> options = new List < Map < String, String >> ();
        
        Map<String, String> mapPickListValues = new Map<String, String>();
		Schema.SObjectType objSobjectType = Schema.getGlobalDescribe().get(strObjectName);
		Schema.DescribeSObjectResult objDescribeSobject = objSobjectType.getDescribe();
		Map<String, Schema.SObjectField> mapFields = objDescribeSobject.fields.getMap();
		List<Schema.PicklistEntry> lstPickListValues = mapFields.get(strPicklistField).getDescribe().getPickListValues();
		for (Schema.PicklistEntry objPickList : lstPickListValues) {
              Map < String, String > values = new Map < String, String > {
                'label' => objPickList.getLabel(),
                'value' => objPickList.getValue()
            };
            options.add(values);
    		System.debug('Value = ' +objPickList.getValue() +' , Label = ' +objPickList.getLabel());
		}
        System.debug('options-->>'+options);
        return options;
    } 



    @AuraEnabled
    public static void saveValues(Id recordid, String lostReason, String comment) {
        Opportunity opp = [select id,Reason__c ,Comments__c from Opportunity where Id=: recordid];
        opp.Reason__c  = lostReason;
        opp.Comments__c = comment;
        System.debug('opp-->>'+opp);
        update opp;
    }
    
}