force-app/main/default/objects/Opportunity/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Budget Cut</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Failed Trial</fullName>
            </value>
            <value>
                <fullName>Integration Issues</fullName>
            </value>
            <value>
                <fullName>Stopped responding</fullName>
            </value>
            <value>
                <fullName>No Interest</fullName>
            </value>
            <value>
                <fullName>Not a fit (rejected by InMobi)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Admin Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityStageControllerTest.cls
@isTest
private class OpportunityStageControllerTest {
    @isTest
    static void testGetPickListValues() {
        // Call the method being tested
        List<Map<String, String>> picklistValues = OpportunityStageController.getPickListValues('Opportunity', 'StageName');
    }

    @isTest(SeeAllData=true)
    static void testSaveValues() {
        // Create a test opportunity
		Opportunity testOpportunity = [SELECT Id,Reason__c, Comments__c FROM Opportunity LIMIT 1 ];

        // Call the method being tested
        OpportunityStageController.saveValues(testOpportunity.Id, 'Lost', 'Test Comment');

        // Retrieve the updated opportunity
        Opportunity updatedOpportunity = [SELECT Id, Reason__c, Comments__c FROM Opportunity WHERE Id = :testOpportunity.Id];

        // Assert the results
        System.assertEquals('Lost', updatedOpportunity.Reason__c);
        System.assertEquals('Test Comment', updatedOpportunity.Comments__c);
    }
}